{"name": "test_login_2", "status": "passed", "description": "登录失败--错误的手机号", "attachments": [{"name": "log", "source": "a105f47c-deb8-4fe1-b857-073888c29966-attachment.txt", "type": "text/plain"}], "start": 1610770851008, "stop": 1610770851214, "uuid": "6e2872e6-b045-42e0-9b16-936abe26aa60", "historyId": "cd55a8ebf69949af490ca6af0e81f054", "testCaseId": "479b997c2849f2f0285747f1d15ac239", "fullName": "testcases.test_login.Test_Login#test_login_2", "labels": [{"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "Test_Login"}, {"name": "host", "value": "yantianpeng.local"}, {"name": "thread", "value": "34298-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_login"}]}