{"name": "test_01[4]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 3 == 4", "trace": "self = <test_case_04.Test_abc_03 object at 0x111611460>, before = 4\n\n    def test_01(self,before):\n        print(\"----->>>>我是测试方法<<<<----\");\n>       assert 3 == before;\nE       assert 3 == 4\n\ntest_case_04.py:24: AssertionError"}, "attachments": [{"name": "stdout", "source": "1917fbb4-0995-48b1-9c41-25e6819722c3-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "before", "value": "4"}], "start": 1610631584751, "stop": 1610631584751, "uuid": "ea8dc948-b0f1-4591-a923-b34d83bc1b3e", "historyId": "10ac3fd820254cc58b9859f53e8cb28c", "testCaseId": "f7eb19b8d4e9053f77f9cc806fb477e7", "fullName": "test_case_04.Test_abc_03#test_01", "labels": [{"name": "suite", "value": "test_case_04"}, {"name": "subSuite", "value": "Test_abc_03"}, {"name": "host", "value": "yantianpeng.local"}, {"name": "thread", "value": "28416-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case_04"}]}