{"name": "test_01[4]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 3 == 4", "trace": "self = <test_case_04.Test_abc_03 object at 0x103bcb640>, before = 4\n\n    def test_01(self,before):\n        print(\"----->>>>我是测试方法<<<<----\");\n>       assert 3 == before;\nE       assert 3 == 4\n\ntest_case_04.py:24: AssertionError"}, "attachments": [{"name": "stdout", "source": "4585a1d2-df85-463d-9f31-b45040a46ecd-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "before", "value": "4"}], "start": 1610631531201, "stop": 1610631531202, "uuid": "d8d18f4a-44cd-44b9-9495-7ce955f50a27", "historyId": "10ac3fd820254cc58b9859f53e8cb28c", "testCaseId": "f7eb19b8d4e9053f77f9cc806fb477e7", "fullName": "test_case_04.Test_abc_03#test_01", "labels": [{"name": "suite", "value": "test_case_04"}, {"name": "subSuite", "value": "Test_abc_03"}, {"name": "host", "value": "yantianpeng.local"}, {"name": "thread", "value": "28373-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case_04"}]}