{"name": "test_02", "status": "failed", "statusDetails": {"message": "AssertionError: assert False\n +  where False = hasattr('hello', 'hello')", "trace": "self = <test_case.TestCase object at 0x1112af640>, function_fixture = 4\n\n    def test_02(self,function_fixture):\n        x= \"hello\";\n>       assert  hasattr(x,\"hello\");\nE       AssertionError: assert False\nE        +  where False = hasattr('hello', 'hello')\n\ntest_case.py:68: AssertionError"}, "attachments": [{"name": "stdout", "source": "95f516cb-4559-4e0b-9c7d-d5b6c895c27c-attachment.txt", "type": "text/plain"}], "start": 1610631584712, "stop": 1610631584712, "uuid": "0a551087-21d0-4036-9a0e-963239487e3a", "historyId": "fd40a68d1293a4216575724249f169a6", "testCaseId": "2a1103500c0e5c080c4a1cbdca380ae1", "fullName": "test_case.TestCase#test_02", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('class_fixture')"}, {"name": "suite", "value": "test_case"}, {"name": "subSuite", "value": "TestCase"}, {"name": "host", "value": "yantianpeng.local"}, {"name": "thread", "value": "28416-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case"}]}